version: '3.9'

services:
  backend:
    build:
      context: ./ghg-worldbank-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./ghg-worldbank-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend